# Generated by Django 4.1 on 2023-07-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
