# Generated by Django 4.1 on 2023-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_file_file_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date', '-id'), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='group',
            name='resume',
            field=models.CharField(default='Empty', max_length=35, verbose_name='Резюме'),
            preserve_default=False,
        ),
    ]
