# Generated by Django 4.1 on 2023-06-15 07:19

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Максимум 500 знаков.', max_length=500, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corporate_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Формат: +99999999999', max_length=128, null=True, region=None, unique=True, verbose_name='Корпоративный номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания аккаунта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Корпоративная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Указывает возможность пользователя войти на портал. Снимите чекбокс вместо удаления учетной записи.', verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти на этот сайт с правами администратора.', verbose_name='Статус администратора'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Личная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personal_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Формат: +99999999999', max_length=128, null=True, region=None, unique=True, verbose_name='Личный номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photo/', verbose_name='Фотография'),
        ),
    ]
