# Generated by Django 4.1 on 2023-07-09 09:04

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Корпоративная почта')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Личная почта')),
                ('corporate_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Формат: +99999999999', max_length=128, null=True, region=None, unique=True, verbose_name='Корпоративный номер телефона')),
                ('personal_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Формат: +99999999999', max_length=128, null=True, region=None, unique=True, verbose_name='Личный номер телефона')),
                ('birthday_date', models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД/ДД.ММ.ГГГГ', null=True, verbose_name='День рождения')),
                ('bio', models.TextField(blank=True, help_text='Максимум 500 знаков.', max_length=500, null=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photo/', verbose_name='Фотография')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания аккаунта')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти на этот сайт с правами администратора.', verbose_name='Статус администратора')),
                ('is_active', models.BooleanField(default=True, help_text='Указывает возможность пользователя войти на портал. Снимите чекбокс вместо удаления учетной записи.', verbose_name='Статус активности')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-date_joined',),
            },
        ),
    ]
