# Generated by Django 4.1 on 2023-06-10 03:33

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last_name')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='middle_name')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='job_title')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='personal_email')),
                ('corporate_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Format: +99999999999', max_length=128, null=True, region=None, unique=True, verbose_name='phone_number')),
                ('personal_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Format: +99999999999', max_length=128, null=True, region=None, unique=True, verbose_name='phone_number')),
                ('birthday_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='birthday_date')),
                ('bio', models.TextField(blank=True, help_text='Maximum 500 characters.', max_length=500, null=True, verbose_name='bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photo/', verbose_name='Users Photo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-date_joined',),
            },
        ),
    ]
