# Generated by Django 4.1 on 2023-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_alter_customuser_bio_alter_customuser_birthday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД, ДД.ММ.ГГГГ', null=True, verbose_name='День рождения'),
        ),
    ]
