# Generated by Django 4.1 on 2023-07-12 07:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Личная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personal_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Формат: +99999999999', max_length=128, null=True, region=None, verbose_name='Личный номер телефона'),
        ),
    ]
