swagger: '2.0'
info:
  title: CSN API
  description: CSN project documentation
  version: v1
securityDefinitions:
  Basic:
    type: basic
consumes:
- application/json
produces:
- application/json
security:
- Basic: []
paths:
  "/addressbook":
    get:
      operationId: addressbook_list
      description: Create address book view.
      parameters:
      - name: search
        in: query
        description: A search term.
        required: false
        type: string
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  "$ref": "#/definitions/AddressBook"
      tags:
      - addressbook
    parameters: []
  "/auth/token/login/":
    post:
      operationId: auth_token_login_create
      description: Use this endpoint to obtain user authentication token.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/TokenCreate"
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/TokenGetResponse"
      tags:
      - auth
    parameters: []
  "/auth/token/logout/":
    post:
      operationId: Удаление токена
      description: Deletes the current user's token
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - auth
    parameters: []
  "/birthday_list/":
    get:
      operationId: birthday_list_list
      description: Сериалайзер для дней рождения
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              "$ref": "#/definitions/Birthday"
      tags:
      - birthday_list
    parameters: []
  "/posts/":
    get:
      operationId: posts_list
      description: Добавление, изменение и удаление постов. Получение списка постов.
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  "$ref": "#/definitions/Post"
      tags:
      - posts
    post:
      operationId: posts_create
      description: Добавление, изменение и удаление постов. Получение списка постов.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/Post"
      responses:
        '201':
          description: ''
          schema:
            "$ref": "#/definitions/Post"
      tags:
      - posts
    parameters: []
  "/posts/{id}/":
    get:
      operationId: posts_read
      description: Добавление, изменение и удаление постов. Получение списка постов.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/Post"
      tags:
      - posts
    put:
      operationId: posts_update
      description: Добавление, изменение и удаление постов. Получение списка постов.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/Post"
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/Post"
      tags:
      - posts
    patch:
      operationId: posts_partial_update
      description: Добавление, изменение и удаление постов. Получение списка постов.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/Post"
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/Post"
      tags:
      - posts
    delete:
      operationId: posts_delete
      description: Добавление, изменение и удаление постов. Получение списка постов.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - posts
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пост.
      required: true
      type: integer
  "/posts/{id}/like/":
    post:
      operationId: posts_like_create
      description: Лайкнуть пост, отменить лайк.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/Post"
      responses:
        '201':
          description: ''
          schema:
            "$ref": "#/definitions/Post"
      tags:
      - posts
    delete:
      operationId: posts_like_delete
      description: Лайкнуть пост, отменить лайк.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - posts
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пост.
      required: true
      type: integer
  "/users/":
    get:
      operationId: users_list
      description: Users view.
      parameters:
      - name: limit
        in: query
        description: Number of results to return per page.
        required: false
        type: integer
      - name: offset
        in: query
        description: The initial index from which to return the results.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  "$ref": "#/definitions/User"
      tags:
      - users
    parameters: []
  "/users/me/":
    get:
      operationId: users_me
      description: Users view.
      parameters:
      - name: limit
        in: query
        description: Number of results to return per page.
        required: false
        type: integer
      - name: offset
        in: query
        description: The initial index from which to return the results.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/User"
      tags:
      - users
    parameters: []
  "/users/registration/":
    post:
      operationId: users_registration_create
      description: Create users view.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/CreateCustomUser"
      responses:
        '201':
          description: ''
          schema:
            "$ref": "#/definitions/CreateUserResponse"
      tags:
      - users
    parameters: []
  "/users/set_password/":
    post:
      operationId: users_set_password_create
      description: Change password view.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/ChangePassword"
      responses:
        '200':
          description: 'Password updated successfully'
      tags:
      - users
    parameters: []
  "/users/short_info/{user_id}/":
    get:
      operationId: users_short_info_list
      description: Short info about user.
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  "$ref": "#/definitions/ShortInfo"
      tags:
      - users
    parameters:
    - name: user_id
      in: path
      required: true
      type: string
  "/users/{id}/":
    get:
      operationId: users_read
      description: Users view.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/User"
      tags:
      - users
    put:
      operationId: users_update
      description: Users view.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/UserUpdate"
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/UserUpdate"
      tags:
      - users
    patch:
      operationId: users_partial_update
      description: Users view.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          "$ref": "#/definitions/UserUpdate"
      responses:
        '200':
          description: ''
          schema:
            "$ref": "#/definitions/UserUpdate"
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
  "/users/{id}/posts/":
    get:
      operationId: users_posts
      description: Users view.
      parameters: []
      responses:
        '200':
          schema:
            type: object
            properties:
              count:
                type: integer
                example: 1
                description: 'Общее количество постов'
              next:
                type: string
                format: uri
                example: null
                description: 'Ссылка на следующую страницу'
              previous:
                type: string
                format: uri
                example: null
                description: 'Ссылка на предыдущую страницу'
              results:
                type: array
                items:
                  $ref: '#/definitions/Post'
                description: 'Список постов'
          description: ''
      tags:
      - users
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Пользователь.
      required: true
      type: integer
definitions:
  AddressBook:
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      email:
        title: Email
        type: string
        readOnly: true
        minLength: 1
      first_name:
        title: Имя
        type: string
        maxLength: 150
        x-nullable: true
      middle_name:
        title: Отчество
        type: string
        maxLength: 150
        x-nullable: true
      last_name:
        title: Фамилия
        type: string
        maxLength: 150
        x-nullable: true
      job_title:
        title: Должность
        type: string
        maxLength: 150
        x-nullable: true
      corporate_phone_number:
        title: Корпоративный номер телефона
        description: 'Формат: +99999999999'
        type: string
        maxLength: 128
        x-nullable: true
      photo:
        title: Фотография
        type: string
        readOnly: true
        x-nullable: true
        format: uri
  TokenCreate:
    type: object
    properties:
      password:
        title: Password
        type: string
        minLength: 1
      email:
        title: Email
        type: string
        minLength: 1
  TokenGetResponse:
    type: object
    properties:
      auth_token:
        title: Auth. token
        type: string
  Birthday:
    required:
    - birthday_date
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      photo:
        title: Фотография
        type: string
        readOnly: true
        x-nullable: true
        format: uri
      first_name:
        title: Имя
        type: string
        maxLength: 150
        x-nullable: true
      last_name:
        title: Фамилия
        type: string
        maxLength: 150
        x-nullable: true
      birthday_date:
        title: Birthday date
        type: string
        format: date
  User:
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      email:
        title: Email
        type: string
        readOnly: true
        minLength: 1
      first_name:
        title: Имя
        type: string
        maxLength: 150
        x-nullable: true
      last_name:
        title: Фамилия
        type: string
        maxLength: 150
        x-nullable: true
      middle_name:
        title: Отчество
        type: string
        maxLength: 150
        x-nullable: true
      job_title:
        title: Должность
        type: string
        maxLength: 150
        x-nullable: true
      personal_email:
        title: Личная почта
        type: string
        format: email
        maxLength: 254
        x-nullable: true
      corporate_phone_number:
        title: Корпоративный номер телефона
        description: 'Формат: +99999999999'
        type: string
        maxLength: 128
        x-nullable: true
      personal_phone_number:
        title: Личный номер телефона
        description: 'Формат: +99999999999'
        type: string
        maxLength: 128
        x-nullable: true
      birthday_day:
        title: Birthday day
        type: string
        readOnly: true
      birthday_month:
        title: Birthday month
        type: string
        readOnly: true
      bio:
        title: Биография
        description: Максимум 500 знаков.
        type: string
        maxLength: 500
        x-nullable: true
      photo:
        title: Photo
        type: string
        readOnly: true
      department:
        title: Подразделение
        type: string
        maxLength: 50
        x-nullable: true
  Image:
    type: object
    properties:
      image_link:
        title: Image link
        type: string
        readOnly: true
        format: uri
  Post:
    required:
    - text
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      text:
        title: Текст
        type: string
        maxLength: 40000
        minLength: 1
      author:
        "$ref": "#/definitions/User"
      pub_date:
        title: Дата создания
        type: string
        format: date-time
        readOnly: true
      update_date:
        title: Последнее обновление
        type: string
        format: date-time
        readOnly: true
      images:
        type: array
        items:
          "$ref": "#/definitions/Image"
      like_count:
        title: Like count
        type: string
        readOnly: true
      users_like:
        type: array
        items:
          type: integer
        uniqueItems: true
  CreateCustomUser:
    required:
    - email
    - password
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
      password:
        title: Пароль
        type: string
        maxLength: 150
        minLength: 8
  CreateUserResponse:
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
  ChangePassword:
    required:
    - new_password
    - current_password
    type: object
    properties:
      new_password:
        title: New password
        type: string
        minLength: 1
      current_password:
        title: Current password
        type: string
        minLength: 1
  ShortInfo:
    required:
    - posts_count
    type: object
    properties:
      first_name:
        title: Имя
        type: string
        maxLength: 150
        x-nullable: true
      middle_name:
        title: Отчество
        type: string
        maxLength: 150
        x-nullable: true
      job_title:
        title: Должность
        type: string
        maxLength: 150
        x-nullable: true
      posts_count:
        title: Posts count
        type: integer
  UserUpdate:
    required:
    - birthday_day
    - birthday_month
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      email:
        title: Email
        type: string
        readOnly: true
        minLength: 1
      first_name:
        title: Имя
        type: string
        maxLength: 150
        x-nullable: true
      last_name:
        title: Фамилия
        type: string
        maxLength: 150
        x-nullable: true
      middle_name:
        title: Отчество
        type: string
        maxLength: 150
        x-nullable: true
      job_title:
        title: Должность
        type: string
        maxLength: 150
        x-nullable: true
      personal_email:
        title: Личная почта
        type: string
        format: email
        maxLength: 254
        x-nullable: true
      corporate_phone_number:
        title: Корпоративный номер телефона
        description: 'Формат: +99999999999'
        type: string
        maxLength: 128
        x-nullable: true
      personal_phone_number:
        title: Личный номер телефона
        description: 'Формат: +99999999999'
        type: string
        maxLength: 128
        x-nullable: true
      birthday_day:
        title: Birthday day
        type: integer
        x-nullable: true
      birthday_month:
        title: Birthday month
        type: integer
        x-nullable: true
      bio:
        title: Биография
        description: Максимум 500 знаков.
        type: string
        maxLength: 500
        x-nullable: true
      photo:
        title: Photo
        type: string
        readOnly: true
        x-nullable: true
        format: uri
      department:
        title: Подразделение
        type: string
        maxLength: 50
        x-nullable: true